name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install flake8 pytest
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest tests/test_wiki_automation.py -v
    
    - name: Test configuration manager
      run: |
        python scripts/wiki_config_manager.py
    
    - name: Test wiki selector
      run: |
        python scripts/wiki_selector.py --help

  check-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Check JSON files
      run: |
        # Check wiki_config.json
        python -m json.tool wiki_config.json > /dev/null
        echo "wiki_config.json is valid JSON"
        
        # Check user_wikis.json.sample
        python -m json.tool user_wikis.json.sample > /dev/null
        echo "user_wikis.json.sample is valid JSON"

  check-scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Check Python scripts syntax
      run: |
        python -m py_compile scripts/wiki_config_manager.py
        python -m py_compile scripts/wiki_selector.py
        python -m py_compile scripts/wiki_validator.py
        python -m py_compile scripts/wiki_secure_submission.py
        echo "All Python scripts have valid syntax"